# Generated by Django 4.0.4 on 2022-05-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_symptoms_alter_task_options_diseases'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AlterModelOptions(
            name='diseases',
            options={'verbose_name': 'болезнь', 'verbose_name_plural': 'болезни'},
        ),
        migrations.AlterModelOptions(
            name='symptoms',
            options={'verbose_name': 'симптом', 'verbose_name_plural': 'симптомы'},
        ),
        migrations.AddField(
            model_name='symptoms',
            name='therapy',
            field=models.TextField(blank=True, verbose_name='Как лечить'),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='symptoms',
            field=models.ManyToManyField(blank=True, related_name='diseases', to='main.symptoms', verbose_name='Симптомы'),
        ),
    ]
