# Generated by Django 4.0.4 on 2022-05-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_symptoms_therapy'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseases',
            name='therapies',
            field=models.TextField(blank=True, verbose_name='Как лечить'),
        ),
    ]
