# Generated by Django 4.0.4 on 2022-05-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_diseases_therapies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Causes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Причина болезни',
                'verbose_name_plural': 'Причины болезниs',
            },
        ),
        migrations.RemoveField(
            model_name='diseases',
            name='therapies',
        ),
        migrations.AddField(
            model_name='diseases',
            name='causes',
            field=models.ManyToManyField(blank=True, to='main.causes', verbose_name='Причины болезни'),
        ),
    ]
