# Generated by Django 4.0.4 on 2022-05-23 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_causes_remove_diseases_therapies_diseases_causes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='causes',
            options={'verbose_name': 'Причина болезни', 'verbose_name_plural': 'Причины болезней'},
        ),
    ]
